name: cambermast-website
services:
  web:
    image: cambermast-website-dev
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/web/node_modules
    environment:
      - NODE_ENV=development
